# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '3314_graphmodel_jsonldcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmodel',
            name='alias',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
